language: generic
sudo: true

env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
  - EMACS_VERSION=24.3
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=master

matrix:
  allow_failures:
    - env: EMACS_VERSION=master

before_install:
  - sudo apt-get update
  - sudo apt-get install -y aspell aspell-en # required for flyspell test

install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs

script:
  - $EMACS --version
  - emacs=$EMACS make test

notifications:
  email:
    # Default is change, but that includes a new branch's 1st success.
    on_success: never
    on_failure: always
